# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target '도시공존' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
    if target.name == 'Pods-도시공존'
      target.build_configurations.each do |config|
        config.build_settings['PRODUCT_NAME'] = 'Pods_____'
      end
    end
  end
end